#!/usr/bin/env python

Import("env")
Import("env_modules")

env_advanced_animation = env_modules.Clone()

# Godot's own source files
env_advanced_animation.add_source_files(env.modules_sources, "*.cpp")
